version: "3"
services:

  db:
    image: postgres
    container_name: vk_parser_db
    expose:
      - "54302"
    ports:
      - "54302:54302"
    environment:
      - POSTGRES_PASSWORD=grafserega1997
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data/sql:/docker-entrypoint-initdb.d/
    command: -p 54302
    networks:
      - postgres

volumes:
  db-data:

networks:
  postgres:
    driver: bridge
